BoxLayout:
    orientation: "vertical"

    #MDToolbar:
    #    title: "Example Tabs"

    MDTabs:
        id: android_tabs
        on_tab_switch: app.on_tab_switch(*args)


<TabMain>:
    MDLabel:
        id: label
        text: "Tab 0"
        halign: "center"


<TabList>:
    MDLabel:
        id: label
        text: "Tab 0"
        halign: "center"


<TabDetails>:
    MDLabel:
        id: label
        text: "Tab 0"
        halign: "center"

